-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 13:04:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_test` DEFAULT CHARACTER SET utf8 ;
USE `mydb_test` ;

-- -----------------------------------------------------
-- Table `mydb_test`.`usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_test`.`usr` (
  `idusr` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_test`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_test`.`product` (
  `idp` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_test`.`invoces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_test`.`invoces` (
  `idinvoces` INT NOT NULL AUTO_INCREMENT,
  `idusr` INT NOT NULL,
  `idp` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idinvoces`),
  INDEX `usr_idx` (`idusr` ASC) VISIBLE,
  INDEX `prod_idx` (`idp` ASC) VISIBLE,
  CONSTRAINT `usr`
    FOREIGN KEY (`idusr`)
    REFERENCES `mydb_test`.`usr` (`idusr`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `prod`
    FOREIGN KEY (`idp`)
    REFERENCES `mydb_test`.`product` (`idp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
